# 常量

函数原型

In [1]:
import tensorflow as tf
import numpy as np

# https://tensorflow.google.cn/versions/r2.3/api_docs/python/tf/constant?hl=en
# tf.constant(
#     value, dtype=None, shape=None, name='Const'
# )

直接定义常量

In [2]:
const_001 = tf.constant([1, 2, 3, 4, 5, 6])
print('const_001 = ', const_001)

const_001 =  tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


<br/>将numpy数组转换成常量

In [3]:
numpy_const_001 = np.array(np.array([[1, 2, 3], [4, 5, 6]]))
const_002 = tf.constant(numpy_const_001)
print('const_002 = ', const_002)

const_002 =  tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<br/>`dtype`属性会根据数据的类型自动确定

In [4]:
print('const_001 dtype = ', const_001.dtype)

const_001 dtype =  <dtype: 'int32'>


<br/>如果手工指定了`dtype`，则数据会自动进行转换

In [5]:
const_001_float32 = tf.constant([1, 2, 3, 4, 5, 6], dtype=tf.float32)
print('const_001_float32 = ', const_001_float32)
print('const_001_float32 dtype = ', const_001_float32.dtype)

const_001_float32 =  tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float32)
const_001_float32 dtype =  <dtype: 'float32'>


对比`const_001`的输出，不难看出，数据类型已经发生了改变.<br/><br/>

如果在创建常量的同时，给定了形状`shape`，tf会自动尝试按照指定的形状进行填充

In [6]:
const_003_with_shape = tf.constant(np.array([1, 2, 3, 4, 5, 6]), shape=(3, 2))
print('const_003_with_shape = ', const_003_with_shape)

const_003_with_shape =  tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


<br/>即使传入数据的形状与`shape`参数不相同，数据也会按照`shape`进行重新填充

In [7]:
const_004_with_shape = tf.constant(np.array(np.array([[1, 2, 3], [4, 5, 6]])), shape=(3, 2))
print('const_004_with_shape = ', const_004_with_shape)

const_004_with_shape =  tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


# 常量计算

## 常数计算

In [8]:
x = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
y = x + 2
print('y1 = ', y)

y1 =  tf.Tensor(
[[3. 4.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [9]:
y = x * 3
print('y2 = ', y)

y2 =  tf.Tensor(
[[ 3.  6.]
 [ 9. 12.]], shape=(2, 2), dtype=float32)


In [10]:
y = x ** 2
print('y3 = ', y)

y3 =  tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]], shape=(2, 2), dtype=float32)


In [11]:
y = x / 3
print('y4 = ', y)

y4 =  tf.Tensor(
[[0.33333334 0.6666667 ]
 [1.         1.3333334 ]], shape=(2, 2), dtype=float32)


注意：若定义`x = tf.constant([[1, 2], [3, 4]], dtype=tf.int8)`，则会报错
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Value
for attr 'T' of int8 is not in the list of allowed values: bfloat16, float, half, double, int32, int64, complex64,
complex128; NodeDef: {{node Pow}}; Op < name = Pow;
signature = x:T, y: T -> z: T;
attr = T:type, allowed = [DT_BFLOAT16, DT_FLOAT, DT_HALF, DT_DOUBLE, DT_INT32, DT_INT64, DT_COMPLEX64,
                          DT_COMPLEX128] > [Op:Pow]
```
<br/><br/>

## 两个常量计算

In [12]:
x1 = tf.constant([[11, 12], [21, 22]], dtype=tf.float32)
x2 = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

In [13]:
y = x1 + x2
print('y5 = ', y)

y5 =  tf.Tensor(
[[16. 18.]
 [28. 30.]], shape=(2, 2), dtype=float32)


In [14]:
y = x1 - x2
print('y6 = ', y)

y6 =  tf.Tensor(
[[ 6.  6.]
 [14. 14.]], shape=(2, 2), dtype=float32)


In [15]:
y = x1 * x2
print('y7 = ', y)

y7 =  tf.Tensor(
[[ 55.  72.]
 [147. 176.]], shape=(2, 2), dtype=float32)


In [16]:
y = x1 / x2
print('y8 = ', y)

y8 =  tf.Tensor(
[[2.2  2.  ]
 [3.   2.75]], shape=(2, 2), dtype=float32)


In [17]:
y = pow(x1, 1 / 2)
print('y9 = ', y)

y9 =  tf.Tensor(
[[3.3166249 3.4641016]
 [4.5825763 4.690416 ]], shape=(2, 2), dtype=float32)
